name: Build Android APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: codepoet/kivy-buildozer-android-docker:latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with Buildozer
      run: |
        # Create fonts directory and copy font
        mkdir -p fonts
        cp /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf fonts/simsun.ttf
        
        # Give buildozer permissions to directory
        chown -R user:user .
        
        # Build APK with buildozer
        su user -c "buildozer android debug"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
        retention-days: 90