name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build with Kivy Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create minimal app
        run: |
          # Create a minimal Kivy app
          cat > main.py << EOF
          from kivy.app import App
          from kivy.uix.label import Label
          
          class TestApp(App):
              def build(self):
                  return Label(text='Hello Kivy World!')
          
          if __name__ == '__main__':
              TestApp().run()
          EOF
          
          # Create minimal buildozer.spec
          cat > buildozer.spec << EOF
          [app]
          title = Test App
          package.name = testapp
          package.domain = org.test
          source.dir = .
          source.include_exts = py
          version = 0.1
          requirements = python3,kivy
          
          android.api = 30
          android.minapi = 21
          
          [buildozer]
          log_level = 2
          EOF

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build APK with Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd \
            kivy/buildozer:latest \
            bash -c "cd /home/user/hostcwd && buildozer android debug"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: testapp-debug-apk
          path: bin/*.apk
          if-no-files-found: error