name: Build Android APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            libpango1.0-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            xvfb \
            xauth \
            automake \
            autoconf \
            libtool \
            pkg-config \
            ccache \
            libncurses5:i386 \
            libstdc++6:i386 \
            libgtk2.0-0:i386 \
            libpangox-1.0-0:i386 \
            libpangoxft-1.0-0:i386 \
            libidn11:i386 \
            zip \
            unzip \
            openjdk-8-jdk

    - name: Build with Buildozer
      run: |
        # Copy font file
        mkdir -p fonts
        cp /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf fonts/simsun.ttf
        
        # Build APK
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
        retention-days: 90 