name: Build Android APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        # Update apt repositories
        sudo apt-get update
        
        # Install required packages
        sudo apt-get install -y \
          build-essential \
          libsqlite3-dev \
          zlib1g-dev \
          libncurses5-dev \
          libgdbm-dev \
          libnss3-dev \
          libssl-dev \
          libreadline-dev \
          libffi-dev \
          wget \
          lzma \
          liblzma-dev \
          tk-dev
        
        # Setup Python
        python -m pip install --upgrade pip
        pip install buildozer Cython==0.29.33

    - name: Build APK
      run: |
        # Create fonts directory and copy file
        mkdir -p fonts
        echo "Creating placeholder font file"
        touch fonts/simsun.ttf
        
        # Build debug APK
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
        retention-days: 90